version: "3.8"

services:
  dev:
    container_name: django_wait_for_databases
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - RUFF_CACHE_DIR=/tmp/.ruff_cache
      - POETRY_PYPI_TOKEN_PYPI=${POETRY_PYPI_TOKEN_PYPI}
      - POETRY_HTTP_BASIC_PYPI_USERNAME=${POETRY_HTTP_BASIC_PYPI_USERNAME}
      - POETRY_HTTP_BASIC_PYPI_PASSWORD=${POETRY_PYPI_TOKEN_PYPI}

    volumes:
      - .:/workspaces
    working_dir: /workspaces
    entrypoint: /workspaces/.devcontainer/entrypoint.sh
    command: sleep infinity
